server:
  port: 8080
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/llldddbbb/spring-cloud-config-repo.git
          username:
          password:

