server:
  port: 8001
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: provider-user

logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
eureka:
  client:
    service-url:
      defauleZone: http://localhost:8761/eureka/
  #表示把自己的IP注册到Eureka Server
  instance:
    prefer-ip-address: true
